server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
        #匹配后提供服务的路由地址 通过服务名动态路由
          uri: lb://mcroserviceprovide
          #uri: http://localhost:8001
          predicates:
            #- Path=/payment/get/** # 断言，路径相匹配的进行路由
            - After=2022-10-24T10:11:12.763+08:00[Asia/Shanghai]
       # - id: payment_route2
        #  uri: http://localhost:8001
         # predicates:
          #  Path=/payment/lb/** #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka8095.com:8095/eureka